name: bits_and_sats_frontend
description: Bits and Sats.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  socket_io_client: ^1.0.2
  provider: ^6.0.3
  flutter_svg: ^1.1.0
  js: ^0.6.4
  url_launcher: ^6.1.3
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #       - asset: assets/fonts/Montserrat-ExtraBold.ttf
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  assets:
    - assets/icons/
    - assets/images/